"""Live observation interfaces for future realtime monitoring.

This package intentionally contains only source-agnostic data contracts for
now. OCR, manual UI input, and future packet capture should all emit the same
observation events before anything is merged into ``SessionObs``.
"""

from bidking_lab.live.types import (
    AuctionPhase,
    FieldUpdate,
    GRID_COLUMNS,
    GridFootprint,
    GridItemObservation,
    LiveEventKind,
    LiveObservationBatch,
    ObservationSource,
    SourceConfidence,
    event_requests_recompute,
    grid_footprint,
    shape_key_dimensions,
    source_priority,
)
from bidking_lab.live.state import (
    LiveSessionState,
    ObservedField,
    apply_observation_batch,
    live_inference_status,
    live_session_matches_context,
    live_state_to_session_obs,
    mark_ready,
    should_replace_field,
    summarize_blocked_field_updates,
    summarize_field_sources,
    summarize_selected_field_sources,
)
from bidking_lab.live.compare import (
    compare_session_obs,
    flatten_session_obs,
    sessions_match,
)
from bidking_lab.live.legacy import (
    legacy_obs_fields,
    live_batch_from_legacy_obs,
)
from bidking_lab.live.packet import live_batch_from_packet_fixture
from bidking_lab.live.layout import (
    DEFAULT_LAYOUT_ESTIMATE_POLICY,
    SAMPLE_FIT_LAYOUT_ESTIMATE_POLICY,
    LayoutEvidence,
    LayoutEstimatePolicy,
    LayoutGridItemView,
    LayoutGridView,
    LayoutItemEvidence,
    LayoutWarehouseEstimate,
    estimate_warehouse_from_layout,
    latest_grid_batch,
    layout_evidence_from_batch,
    layout_evidence_from_batches,
    layout_grid_view,
    layout_item_from_grid_item,
    layout_risk_label,
)
from bidking_lab.live.fatbeans import (
    latest_player_bids,
    live_batches_from_fatbeans_capture,
    live_batches_from_fatbeans_capture_payload,
    parse_fatbeans_capture,
    parse_fatbeans_capture_payload,
)
from bidking_lab.live.replay import (
    LayoutReplayStage,
    ReplayFinalTruth,
    final_truth_from_events,
    layout_replay_stages,
)
from bidking_lab.live.evaluation import (
    FatbeansLayoutEvaluation,
    FatbeansLayoutEvaluationError,
    FatbeansLayoutEvaluationSummary,
    FatbeansLayoutSampleRow,
    LayoutPolicyFit,
    evaluate_fatbeans_layout_capture,
    evaluate_fatbeans_layout_events,
    evaluate_fatbeans_layout_path,
    fit_layout_estimate_policy,
    layout_sample_rows_from_stages,
    summarize_fatbeans_layout_evaluation,
)
from bidking_lab.live.monitor import (
    MonitorTables,
    build_monitor_artifact_from_events,
    build_monitor_artifact_from_file,
    build_monitor_artifact_from_payload,
    load_monitor_tables,
    write_monitor_logs,
)

__all__ = (
    "AuctionPhase",
    "FieldUpdate",
    "GRID_COLUMNS",
    "GridFootprint",
    "GridItemObservation",
    "LiveEventKind",
    "LiveObservationBatch",
    "ObservationSource",
    "SourceConfidence",
    "LiveSessionState",
    "ObservedField",
    "apply_observation_batch",
    "live_inference_status",
    "live_session_matches_context",
    "live_state_to_session_obs",
    "mark_ready",
    "should_replace_field",
    "summarize_blocked_field_updates",
    "summarize_field_sources",
    "summarize_selected_field_sources",
    "compare_session_obs",
    "flatten_session_obs",
    "sessions_match",
    "legacy_obs_fields",
    "live_batch_from_legacy_obs",
    "live_batch_from_packet_fixture",
    "DEFAULT_LAYOUT_ESTIMATE_POLICY",
    "SAMPLE_FIT_LAYOUT_ESTIMATE_POLICY",
    "LayoutEvidence",
    "LayoutEstimatePolicy",
    "LayoutGridItemView",
    "LayoutGridView",
    "LayoutItemEvidence",
    "LayoutWarehouseEstimate",
    "estimate_warehouse_from_layout",
    "latest_grid_batch",
    "layout_evidence_from_batch",
    "layout_evidence_from_batches",
    "layout_grid_view",
    "layout_item_from_grid_item",
    "layout_risk_label",
    "latest_player_bids",
    "live_batches_from_fatbeans_capture",
    "live_batches_from_fatbeans_capture_payload",
    "parse_fatbeans_capture",
    "parse_fatbeans_capture_payload",
    "LayoutReplayStage",
    "ReplayFinalTruth",
    "final_truth_from_events",
    "layout_replay_stages",
    "FatbeansLayoutEvaluation",
    "FatbeansLayoutEvaluationError",
    "FatbeansLayoutEvaluationSummary",
    "FatbeansLayoutSampleRow",
    "LayoutPolicyFit",
    "evaluate_fatbeans_layout_capture",
    "evaluate_fatbeans_layout_events",
    "evaluate_fatbeans_layout_path",
    "fit_layout_estimate_policy",
    "layout_sample_rows_from_stages",
    "summarize_fatbeans_layout_evaluation",
    "MonitorTables",
    "build_monitor_artifact_from_events",
    "build_monitor_artifact_from_file",
    "build_monitor_artifact_from_payload",
    "load_monitor_tables",
    "write_monitor_logs",
    "event_requests_recompute",
    "grid_footprint",
    "shape_key_dimensions",
    "source_priority",
)
