"""v3 inference scaffolding.

The initial v3 package is diagnostic-only. It records evidence semantics and
coverage before any posterior or live decision path is moved off v2.
"""

from bidking_lab.inference.v3.coverage import (
    EvidenceCoverageReport,
    audit_fatbeans_events,
    audit_fatbeans_paths,
)
from bidking_lab.inference.v3.calibration import (
    PriorCalibrationEntry,
    V3PriorCalibrationReport,
    calibrate_posterior_report,
    empty_prior_calibration_flat_dict,
    entry_from_mapping,
    load_prior_calibration_entries,
    propose_prior_calibration,
)
from bidking_lab.inference.v3.constraints import (
    ConstraintConflict,
    ConstraintSet,
    HardNumericConstraint,
    ItemAnchor,
    QualityFloorAnchor,
    ShapeAnchor,
    SoftNumericConstraint,
    compile_hard_constraints,
)
from bidking_lab.inference.v3.events import EvidenceEvent, events_from_fatbeans
from bidking_lab.inference.v3.evidence_registry import (
    ACTION_RESULT_SPECS,
    PUBLIC_INFO_SPECS,
    SKILL_REVEAL_SPECS,
    EvidenceSpec,
    action_result_spec,
    public_info_semantic,
    public_info_semantics_dict,
    public_info_spec,
    skill_reveal_spec,
)
from bidking_lab.inference.v3.posterior import (
    V3PosteriorReport,
    empty_posterior_flat_dict,
    estimate_component_count_cell_value_posterior_from_truths,
    estimate_count_cell_value_posterior_from_truths,
    estimate_q6_posterior_from_truths,
    estimate_residual_count_cell_value_posterior_from_truths,
    sample_truth_bank,
    truth_matches_feasible_summary,
)
from bidking_lab.inference.v3.pipeline import (
    V3CcvOptions,
    V3ShadowPipelineReport,
    estimate_shadow_pipeline,
)
from bidking_lab.inference.v3.priors import (
    QualityPriorReport,
    SessionPriorReport,
    empty_prior_flat_dict,
    ordinary_shape_replacement_values,
    summarize_drop_prior,
    summarize_drop_prior_flat_dict,
)
from bidking_lab.inference.v3.prior_robustness import (
    V3PriorRobustnessReport,
    assess_prior_robustness,
    empty_prior_robustness_flat_dict,
)
from bidking_lab.inference.v3.residual_gate import (
    V3ResidualGateReport,
    empty_residual_gate_flat_dict,
    gate_residual_posterior_report,
)
from bidking_lab.inference.v3.tail_value_review import (
    TailValueReviewEntry,
    V3TailValueReviewReport,
    empty_tail_value_review_flat_dict,
    load_tail_value_review_entries,
    review_tail_value_posterior_report,
    tail_value_review_entry_for,
)
from bidking_lab.inference.v3.underestimate_repair import (
    UnderestimateRepairEntry,
    V3UnderestimateRepairReport,
    empty_underestimate_repair_flat_dict,
    load_underestimate_repair_entries,
    repair_underestimate_posterior_report,
    underestimate_entry_for,
)
from bidking_lab.inference.v3.summary import (
    BucketFeasibleSummary,
    FeasibleSummaryReport,
    compile_feasible_summary,
    empty_feasible_summary_flat_dict,
)
from bidking_lab.inference.v3.truth import (
    DecisionTruthReport,
    QualityTruthReport,
    SettlementTruthReport,
    decision_truth_from_fatbeans,
    decision_truth_from_session_truth,
    empty_decision_truth_flat_dict,
    empty_truth_flat_dict,
    settlement_truth_from_fatbeans,
)

__all__ = (
    "ACTION_RESULT_SPECS",
    "BucketFeasibleSummary",
    "ConstraintConflict",
    "ConstraintSet",
    "DecisionTruthReport",
    "PUBLIC_INFO_SPECS",
    "SKILL_REVEAL_SPECS",
    "EvidenceCoverageReport",
    "EvidenceEvent",
    "EvidenceSpec",
    "FeasibleSummaryReport",
    "HardNumericConstraint",
    "ItemAnchor",
    "PriorCalibrationEntry",
    "QualityFloorAnchor",
    "QualityPriorReport",
    "QualityTruthReport",
    "ShapeAnchor",
    "SoftNumericConstraint",
    "SessionPriorReport",
    "SettlementTruthReport",
    "TailValueReviewEntry",
    "UnderestimateRepairEntry",
    "V3PosteriorReport",
    "V3PriorCalibrationReport",
    "V3PriorRobustnessReport",
    "V3CcvOptions",
    "V3ResidualGateReport",
    "V3ShadowPipelineReport",
    "V3TailValueReviewReport",
    "V3UnderestimateRepairReport",
    "action_result_spec",
    "audit_fatbeans_events",
    "audit_fatbeans_paths",
    "calibrate_posterior_report",
    "compile_hard_constraints",
    "compile_feasible_summary",
    "decision_truth_from_fatbeans",
    "decision_truth_from_session_truth",
    "empty_decision_truth_flat_dict",
    "empty_feasible_summary_flat_dict",
    "empty_posterior_flat_dict",
    "empty_prior_calibration_flat_dict",
    "empty_prior_flat_dict",
    "empty_prior_robustness_flat_dict",
    "empty_residual_gate_flat_dict",
    "empty_tail_value_review_flat_dict",
    "empty_underestimate_repair_flat_dict",
    "empty_truth_flat_dict",
    "entry_from_mapping",
    "estimate_component_count_cell_value_posterior_from_truths",
    "estimate_count_cell_value_posterior_from_truths",
    "estimate_q6_posterior_from_truths",
    "estimate_residual_count_cell_value_posterior_from_truths",
    "estimate_shadow_pipeline",
    "events_from_fatbeans",
    "gate_residual_posterior_report",
    "assess_prior_robustness",
    "load_prior_calibration_entries",
    "load_tail_value_review_entries",
    "load_underestimate_repair_entries",
    "ordinary_shape_replacement_values",
    "propose_prior_calibration",
    "repair_underestimate_posterior_report",
    "review_tail_value_posterior_report",
    "public_info_semantic",
    "public_info_semantics_dict",
    "public_info_spec",
    "sample_truth_bank",
    "settlement_truth_from_fatbeans",
    "skill_reveal_spec",
    "summarize_drop_prior",
    "summarize_drop_prior_flat_dict",
    "truth_matches_feasible_summary",
    "tail_value_review_entry_for",
    "underestimate_entry_for",
)
